version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres-db:5432/prod_db
      - JWT_SECRET_KEY=your_secret_key
      - PORT=5000
    volumes:
      - .:/app
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prod_db
    ports:
      - "5432:5432"
